version: '3.1'

services:
  db:
    image: mysql:8.3.0  
    restart: always  
    environment:
      MYSQL_ROOT_PASSWORD: 13846598527ml  
    ports:
      - "3090:3306"  
    volumes:
      - db_data:/var/lib/mysql  

  adminer:
    image: adminer 
    restart: always  
    ports:
      - "8090:8080"  

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:  
